services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server-john
      - server-paul
      - server-george
      - server-ringo
    ports:
     - "3000:80"

  server-john:
    build: ./nestjs-example
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=John

  server-paul:
    build: ./nestjs-example
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=Paul

  server-george:
    build: ./nestjs-example
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=George

  server-ringo:
    build: ./nestjs-example
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=Ringo

  client:
    build: ./nextjs-example
    links:
      - nginx
    expose:
      - "3001"

  redis:
    image: redis:6
    expose:
      - "6379"
